apiVersion: v1
kind: Service
metadata:
  name: kube-da-svc
  namespace: default
spec:
    type: NodePort
  selector:
    app: kube-da-app
  ports:
    - port: 80
      targetPort: 8080 # порт в нутри

      #      nodePort: 32001 # Порт который пробрасывается прям в миникубу и начинается с 32000
      protocol: TCP
