apiVersion: v1
kind: Service
metadata:
  name: postgres-user-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: postgtres-db
  ports:
    - port: 5432
      targetPort: 5432 # порт в нутри контейнера
      name: postgree-name
      nodePort: 32001 # Порт который пробрасывается прям в миникубу и начинается с 32000
      protocol: TCP