apiVersion: v1
kind: ConfigMap
metadata:
  name: posgtres_user_config
  namespace: default
data:
  USER_POSTGRES_DB_HOST: "127.0.0.1"
  USER_POSTGRES_DB_PORT: "32001"
  USER_POSTGRES_DB_NAME: "POSTGRES"
  USER_POSTGRES_DB_USERNAME: "web_market_user_db"