kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    name: postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/kob/work/MyWork/UniversityProject/postgresVolume/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-volume-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: postgres-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi